#!/bin/bash

## dkeg 2015
## battery status and level driven window borders 
## source in focus.sh -> fcs

. $HOME/bin/colr
## colors 
R=${xcol[4]}    #red
Y=${xcol[6]}    #yellow
G=${xcol[5]}    #green
C=${xcol[9]}    #cyan
N=${xcol[1]}    #bold black

## get the information
BATT=/sys/class/power_supply/BAT0
CAPACITY=$(cat $BATT/capacity)
STATE=$(cat $BATT/status)

## filter and colorize 
 if [ ${STATE} = "Discharging" ] ; then
   case ${CAPACITY} in
   [0-9])  bb="$R" ;;
   [1-2]*) bb="$R" ;;
   [3-6]*) bb="$Y" ;;
   [7-9]*) bb="$G" ;;
   [100])  bb="$G" ;;
   esac
 else 
  bb="$C"
 fi
