#!/bin/sh
# focus_watcher renamed to fw
# and taking benefit functionality from yawee
# modified with wallpaper effects

. $HOME/.bg
# get wall from .xinitrc & set attributes
#wall=$(cat ~/.xinitrc|grep hsetroot|cut -d ' ' -f3|awk '{sub(/&/,"");print}')
#wall=$(cat ~/.xinitrc|grep hsetroot|awk '{sub(/&/,"");print}')
BLUR=20
CON="0.7"
BRT="-0.02"
#dir=$HOME/tmp
#back=$(convert $wall -blur $BLUR $tmp/$pic)
#back=convert "$wall" -blur ${1:-$BLUR} "$dir"/tmpwall.jpg
# bg effects on new window
effect(){
    #hsetroot -fill $back 
    #$wallp -brightness ${1:-$BRT}
    #$wallp -brightness ${1:-$BRT} -blur ${1:-$BLUR}
    #$wallp -blur ${1:-$BLUR} -brightness ${1:-$BRT}
    $wallp -blur ${1:-$BLUR}
    #hsetroot -fill $back
    #$act $opt ${1:-$back}
}

file=fcs

while IFS=: read ev wid; do
    case $ev in
        # window creation
        16) wattr o $wid || corner md $wid 
        test "$(lsw)" = "$wid" && effect ;;
        #test "$(lsw)" = "$wid" ;;

        # mapping requests
        19) wattr o $wid \
            || $file $wid ;;

        # focus next window when deleting focused window
        18) wattr $(pfw) || $file prev 2>/dev/null
            test -z "$(lsw)" && effect 0 ;;
            #test -z "$(lsw)" ;;

        # entering window
        7) wattr o $wid || $file $wid ;;
    esac
done
