#!/bin/bash
# focus_watcher renamed to fw
# and taking benefit functionality from yawee
file=fcs

while IFS=: read ev wid; do
    case $ev in
        # window creation
        16) wattr o $wid || corner md $wid ;;

        # mapping requests
        19) wattr o $wid \
            || $file $wid ;;

        # focus next window when deleting focused window
        18) wattr $(pfw) || $file prev 2>/dev/null;;

        # entering window
        7) wattr o $wid || $file $wid ;;
    esac
done
