#!/bin/sh
# ChefIronBelly 2015
# left, center and right middle placement

CUR=${2:-$(pfw)}
ROOT=$(lsw -r)
SW=$(wattr w $ROOT)
SH=$(wattr h $ROOT)

BW=$(wattr b $CUR)
W=$(wattr w $CUR)
H=$(wattr h $CUR)

X=0
Y=0

case $1 in
    uy) X=$((SW/4 - W/2 - BW))
        Y=$((SH/4 - H/2 - BW));;
     y) X=$((SW/4 - W/2 - BW))
        Y=$((SH/2 - H/2 - BW));;
     g) X=$((SW/2 - W/2 - BW))
        Y=$((SH/2 - H/2 - BW)) ;;
     u) X=$((SW/2 + W/4 - BW*2))
        Y=$((SH/2 - H/2 - BW));;   
esac

wtp $X $Y $W $H $CUR

#mdls=("uy","y","g","u")
#for i in "${mdls[@]}"                           
#  do                                            
#    echo $i                                    
#  done

#  rndm=$i
