#!/bin/bash
. $HOME/bin/colr

FREQ=${FREQ:-0.6}
# use xcolors
#COLORS=${xcol[@]}
COLORS="${xcol[4]} ${xcol[6]} ${xcol[9]} ${xcol[10]}"
#COLORS="${xcol[6]} ${xcol[10]}"

# grab the current border width
BW=$(wattr b $CUR)
while :; do
    for c in $COLORS; do
        CUR=$(pfw)
        BW=$(wattr b $CUR)
        test "`wattr wh $CUR`" != "`wattr wh $(lsw -r)`" && chwb -s $BW -c $c $CUR
        sleep $FREQ
    done
done
