#!/bin/bash
#
# z3bra - 2015 (c) wtfpl
# make the current window "rainbowish"... Awesome idea from xero@nixers.net !
# dkeg twist
# drive pulsing colors based on battery state/level
# only pulse when battery low, else static

. $HOME/bin/colr

FREQ=${FREQ:-0.6}
CHR="${xcol[9]}"
STR="${xcol[5]}"
MED="${xcol[6]}"
LOW="${xcol[4]}" # ${xcol[3]}"
CRIT="${xcol[4]} ${xcol[3]}"
NEUT="${xcol[3]}"

while :; do
  BATT=/sys/class/power_supply/BAT0
  CAPACITY=$(cat $BATT/capacity)
  STATE=$(cat $BATT/status)
        if [ ${STATE} = "Discharging" ] ; then
        case ${CAPACITY} in
          [0-9])  colors="$CRIT" ;;
          [1-2]*) colors="$LOW"  ;;
          [3-6]*) colors="$MED"  ;;
          [7-9]*) colors="$STR"  ;;
          [100])  colors="$STR"  ;;
        esac
        else 
          colors="$CHR"
        fi
    for c in $colors; do
      CUR=$(pfw)
      BW=$(wattr b $CUR)
      test "`wattr wh $CUR`" != "`wattr wh $(lsw -r)`" && chwb -s $BW -c $c $CUR 
      sleep $FREQ
    done
done
