#!/bin/bash
#
# z3bra - 2015 (c) wtfpl
# make the current window "rainbowish"... Awesome idea from xero@nixers.net !
# dkeg twist
# pulsing colors based on battery state/level

. $HOME/bin/colr

## keep battery out of it
## comment out battery lines
#colors="$blu $bblk $ylw"

FREQ=${FREQ:-0.6}

## only pulse when critical
CHR="$cyn"
STR="$grn"
MED="$ylw"
LOW="$red"
CRIT="$red $bblk"

while :; do
  BATT=/sys/class/power_supply/BAT0
  CAPACITY=$(cat $BATT/capacity)
  STATE=$(cat $BATT/status)
  if [ ${STATE} = "Discharging" ] ; then
    case ${CAPACITY} in
      [0-9])  colors="$CRIT" ;;
      [1-2]*) colors="$LOW"  ;;
      [3-6]*) colors="$MED"  ;;
      [7-9]*) colors="$STR"  ;;
      [100])  colors="$STR"  ;;
    esac
  else 
    colors="$CHR"
  fi
    for c in $colors; do
      CUR=$(pfw)
      BW=$(wattr b $CUR)
      chwb -s $BW -c $c $CUR 
      sleep $FREQ
    done
done
