#!/bin/sh
#
# z3bra - 2014 (c) wtfpl
# arrange windows in a tiled pattern
# dkeg update OCT 2015
# awful fix of offset layout if more that 1 window in stacking area

# default values for gaps and master area
PANEL=${PANEL:-0}
GAP=${GAP:-35}
MASTER=${MASTER:-650}

# get current window id and its borderwidth
PFW=$(pfw)
BW=$(wattr b $PFW)
P=$BW/4

# get root window's size (beware, multi-head setups...)
ROOT=$(lsw -r)
SW=$(wattr w $ROOT)
SH=$(wattr h $ROOT)

# get the number of windows to put in the stacking area
MAX=$(lsw|grep -v $PFW|wc -l)

# calculate usable screen size (without borders and gaps)
SW=$((SW - GAP - 2*BW))
SH=$((SH - GAP - 2*BW - PANEL))

Y=$((0 + GAP + PANEL))
# put current window in master area
wtp $GAP $Y $((MASTER - GAP - 2*BW)) $((SH - GAP)) $PFW

# and now, stack up all remaining windows on the right
X=$((MASTER + GAP))
W=$((SW - MASTER - GAP))

# check number of windows for stacking area
# adjust padding calculation accordingly
# horrible , I know
case $MAX in
  1) H=$((SH / MAX - GAP - BW/4-BW/2+BW)) ;;
  2) H=$((SH / MAX - GAP - BW)) ;;
  3) H=$((SH / MAX - GAP - $MAX*BW/2+BW/2-BW/2+$P)) ;;
  4) H=$((SH / MAX - GAP - $MAX*BW/2+BW/2)) ;;
  *) usage 
  #*) H=$((SH / MAX - GAP - 2*BW))
esac

for wid in $(lsw|grep -v $PFW); do
    wtp $X $Y $W $H $wid
    Y=$((Y + H + GAP + 2*BW))
done
